theme: jekyll-theme-cayman
title: Exploring the Architectural Biases of the Canonical Cortical Microcircuit
description: Leveraging RNNs and representational analyses to study the cortical microcircuit, in light of predictive coding
show_downloads: true
google_analytics:
